name: Coverage Report
on:
 push:
   branches:
     - main
 pull_request:
   branches:
     - main
jobs:
 coverage:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout code
       uses: actions/checkout@v3
     - name: Set up JDK 17
       uses: actions/setup-java@v3
       with:
         java-version: '17'
         distribution: 'temurin'
     - name: Build and test with coverage
       run: |
         ./gradlew test jacocoTestReport
     - name: Upload coverage report to Codecov
       uses: codecov/codecov-action@v3
       with:
         token: ${{ secrets.CODECOV_TOKEN }}
         files: build/reports/jacoco/test/jacocoTestReport.xml
